package com.storex.orchestrator.model;

public enum BookingEvent {
    RESERVE_TABLE, TABLE_RESERVED, TABLE_UNAVAILABLE, PROCESS_PAYMENT,
    PAYMENT_SUCCESS, PAYMENT_FAILED, CONFIRM_BOOKING, BOOKING_CONFIRMED
}
